name: Send Scheduled Email

on:
  schedule:
    # Runs at 9 AM and 9 PM UTC daily
    - cron: '20 14,21 * * *'
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Email Function
        run: |
          curl -X GET https://your-vercel-project.vercel.app/api/sendMail
