name: Send Scheduled Email

on:
  schedule:

     - cron: '* * * * *'
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Email Function
        run: |
          curl -X GET https://rem-p3su.vercel.app/api/sendMail
